# Generated by Django 4.1.7 on 2023-03-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='test.png', upload_to='products', verbose_name='Изображение'),
        ),
    ]
