# Generated by Django 4.1.7 on 2023-03-27 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated_date',
            new_name='updated_at',
        ),
    ]
